---
- name: Debug AAP Workflow Variables (Step 2)
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Display ALL available variables for debugging
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
      tags:
        - debug

    - name: Check specific variables we expect from workflow
      ansible.builtin.debug:
        msg:
          - "🔍 Checking Expected AAP Workflow Variables"
          - "=========================================="
          - "incident_sys_id defined: {{ incident_sys_id is defined }}"
          - "incident_number defined: {{ incident_number is defined }}"
          - "servicenow_instance defined: {{ servicenow_instance is defined }}"
          - "workflow_timestamp defined: {{ workflow_timestamp is defined }}"
          - ""
          - "Values (if defined):"
          - "incident_sys_id: {{ incident_sys_id | default('UNDEFINED') }}"
          - "incident_number: {{ incident_number | default('UNDEFINED') }}"
          - "servicenow_instance: {{ servicenow_instance | default('UNDEFINED') }}"
          - "workflow_timestamp: {{ workflow_timestamp | default('UNDEFINED') }}"
      tags:
        - check

    - name: Check if welcome_message from your working example is available
      ansible.builtin.debug:
        msg:
          - "🧪 Testing Working Pattern"
          - "========================="
          - "welcome_message defined: {{ welcome_message is defined }}"
          - "welcome_message value: {{ welcome_message | default('UNDEFINED') }}"
      tags:
        - working_test

    - name: List environment variables that might contain workflow data
      ansible.builtin.debug:
        msg:
          - "🔧 AAP Environment Variables"
          - "============================"
          - "TOWER_JOB_ID: {{ ansible_env.TOWER_JOB_ID | default('Not set') }}"
          - "TOWER_WORKFLOW_JOB_ID: {{ ansible_env.TOWER_WORKFLOW_JOB_ID | default('Not set') }}"
          - "AWX_JOB_ID: {{ ansible_env.AWX_JOB_ID | default('Not set') }}"
      tags:
        - env
