- name: Generate a variable and print it for AAP workflow
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Set a dynamic welcome message
      ansible.builtin.set_fact:
        welcome_message: "Hello from Playbook 1! The current timestamp is {{ ansible_date_time.iso8601 }}"

    - name: Print the welcome message for AAP to capture
      # This debug output is what the AAP workflow will capture.
      ansible.builtin.debug:
        msg: "The_Message_Is: {{ welcome_message }}"
      delegate_to: localhost
      run_once: true