---
- name: Generate a variable and make it available for AAP workflow
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Set a dynamic welcome message
      ansible.builtin.set_fact:
        welcome_message: "Hello from Playbook 1! The current timestamp is {{ ansible_date_time.iso8601 }}"

    - name: Persist the welcome message for the AAP workflow
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_stats:
        data:
          welcome_message: "{{ welcome_message }}"
