---

- name: Set a variable and save to fact cache
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Set a dynamic welcome message
      ansible.builtin.set_fact:
        welcome_message: "Hello from Playbook 1! The current timestamp is {{ ansible_date_time.iso8601 }}"