---

- name: Use a variable passed via AAP workflow
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Print the retrieved variables
      ansible.builtin.debug:
        msg: "Sys ID: {{ incident_sys_id }}"
