---

- name: Use a variable passed via AAP workflow
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Print the retrieved variables
      ansible.builtin.debug:
        msg:
          - "Sys ID: {{ created_incident.record.sys_id }}"
