---
- name: Basic Variable Creation Test (No ServiceNow)
  hosts: localhost
  gather_facts: true
  
  tasks:
    - name: Create test variables (no ServiceNow required)
      ansible.builtin.set_fact:
        test_incident_id: "TEST-{{ ansible_date_time.epoch }}"
        test_incident_number: "INC{{ ansible_date_time.epoch }}"
        test_timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display test variables
      ansible.builtin.debug:
        msg:
          - "📋 Created Test Variables:"
          - "test_incident_id: {{ test_incident_id }}"
          - "test_incident_number: {{ test_incident_number }}"
          - "test_timestamp: {{ test_timestamp }}"

    - name: Set variables for AAP workflow (no conditions)
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_stats:
        data:
          incident_sys_id: "{{ test_incident_id }}"
          incident_number: "{{ test_incident_number }}"
          servicenow_instance: "test.service-now.com"
          workflow_timestamp: "{{ test_timestamp }}"

    - name: Confirm variables were set
      ansible.builtin.debug:
        msg:
          - "✅ Variables set for AAP workflow:"
          - "incident_sys_id: {{ test_incident_id }}"
          - "incident_number: {{ test_incident_number }}"
          - "servicenow_instance: test.service-now.com"
          - "workflow_timestamp: {{ test_timestamp }}"
