---

- name: Use variables passed via AAP workflow
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Display all received workflow variables
      ansible.builtin.debug:
        msg:
          - "📥 Received workflow variables from test_snow_dummy.yml:"
          - "Incident Number: {{ incident_number | default('Not provided') }}"
          - "Sys ID: {{ incident_sys_id | default('Not provided') }}"
          - "State: {{ incident_state | default('Not provided') }}"
          - "Priority: {{ incident_priority | default('Not provided') }}"
          - "Assigned to: {{ incident_assigned_to | default('Not provided') }}"
          - "ServiceNow Instance: {{ servicenow_instance | default('Not provided') }}"

    - name: Simulate incident update operation
      ansible.builtin.debug:
        msg:
          - "🔄 Simulating update to incident {{ incident_number | default('UNKNOWN') }}"
          - "Updating state from '{{ incident_state | default('UNKNOWN') }}' to 'In Progress'"
          - "Target URL: {{ servicenow_instance | default('UNKNOWN') }}/nav_to.do?uri=incident.do?sys_id={{ incident_sys_id | default('UNKNOWN') }}"

    - name: Set updated incident facts
      ansible.builtin.set_fact:
        updated_incident_state: "In Progress"
        updated_by: "AAP Workflow"
        update_timestamp: "{{ ansible_date_time.iso8601 }}"
      
    - name: Display update confirmation
      ansible.builtin.debug:
        msg:
          - "✅ Incident update simulation completed:"
          - "Original State: {{ incident_state | default('UNKNOWN') }}"
          - "New State: {{ updated_incident_state }}"
          - "Updated By: {{ updated_by }}"
          - "Timestamp: {{ update_timestamp }}"
