---

- name: Use a variable passed via AAP workflow
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Print the retrieved variables
      delegate_to: localhost
      run_once: true
      ansible.builtin.debug:
        msg:
          - "Sys ID: {{ incident_sys_id }}"
