---
- name: Simple ServiceNow Update Test (Like playbook_two)
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Test 1 - Check if variables exist (safe check)
      ansible.builtin.set_fact:
        vars_exist:
          incident_sys_id: "{{ incident_sys_id is defined }}"
          incident_number: "{{ incident_number is defined }}"
          servicenow_instance: "{{ servicenow_instance is defined }}"

    - name: Test 2 - Display what we found
      ansible.builtin.debug:
        msg:
          - "🔍 Variable Check Results:"
          - "incident_sys_id exists: {{ vars_exist.incident_sys_id }}"
          - "incident_number exists: {{ vars_exist.incident_number }}"
          - "servicenow_instance exists: {{ vars_exist.servicenow_instance }}"

    - name: Test 3 - Show values if they exist
      ansible.builtin.debug:
        msg:
          - "📋 Variable Values (if available):"
          - "incident_sys_id: {{ incident_sys_id if vars_exist.incident_sys_id else 'NOT_AVAILABLE' }}"
          - "incident_number: {{ incident_number if vars_exist.incident_number else 'NOT_AVAILABLE' }}"
          - "servicenow_instance: {{ servicenow_instance if vars_exist.servicenow_instance else 'NOT_AVAILABLE' }}"

    - name: Test 4 - SUCCESS if all variables available
      ansible.builtin.debug:
        msg:
          - "🎉 SUCCESS! All variables received from AAP workflow"
          - "Ready to proceed with ServiceNow operations"
      when: 
        - vars_exist.incident_sys_id
        - vars_exist.incident_number
        - vars_exist.servicenow_instance

    - name: Test 5 - FAILURE if variables missing
      ansible.builtin.debug:
        msg:
          - "❌ FAILURE! Variables missing from AAP workflow"
          - "This means:"
          - "1. Creation playbook didn't complete successfully"
          - "2. set_stats task didn't execute"
          - "3. Workflow nodes not properly connected"
          - ""
          - "Check the creation playbook logs for the set_stats task"
      when: not (vars_exist.incident_sys_id and vars_exist.incident_number and vars_exist.servicenow_instance)
