---

- name: Mimic ServiceNow ticket details
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Define example ServiceNow variables
      ansible.builtin.set_fact:
        incident_number: 'INC0012345'
        incident_sys_id: 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6'
        incident_state: 'New'
        incident_priority: 'High'
        incident_assigned_to: 'Ansible Automation'
        servicenow_instance: 'https://dev12345.service-now.com'

    - name: Display mock incident details
      ansible.builtin.debug:
        msg:
          - "✅ Incident created successfully!"
          - "Number: {{ incident_number }}"
          - "Sys ID: {{ incident_sys_id }}"
          - "State: {{ incident_state }}"
          - "Priority: {{ incident_priority }}"
          - "Assigned to: {{ incident_assigned_to }}"
          - "URL: {{ servicenow_instance }}/nav_to.do?uri=incident.do?sys_id={{ incident_sys_id }}"