---
# ServiceNow Incident Creation Playbook
# This playbook creates a new incident in ServiceNow
# Designed for Ansible Automation Platform 2.5
# Uses module defaults for credentials and instance configuration

- name: Create ServiceNow Incident
  hosts: localhost
  gather_facts: false
  
  # Module defaults for ServiceNow authentication and instance
  # These will be provided by AAP credential configuration
  module_defaults:
    group/servicenow.itsm.servicenow:
      instance: "{{ servicenow_instance | default(ansible_servicenow_instance) }}"
      username: "{{ servicenow_username | default(ansible_servicenow_username) }}"
      password: "{{ servicenow_password | default(ansible_servicenow_password) }}"
      validate_certs: "{{ servicenow_validate_certs | default(true) }}"

  vars:
    # Default incident properties - can be overridden via survey or extra_vars
    incident_short_description: "{{ incident_title | default('Automated Incident via Ansible') }}"
    incident_description: "{{ incident_details | default('This incident was created automatically by Ansible Automation Platform') }}"
    incident_urgency: "{{ urgency | default('3') }}"  # 1=High, 2=Medium, 3=Low
    incident_impact: "{{ impact | default('3') }}"    # 1=High, 2=Medium, 3=Low
    incident_priority: "{{ priority | default('5') }}" # 1=Critical, 2=High, 3=Moderate, 4=Low, 5=Planning
    incident_state: "{{ state | default('1') }}"      # 1=New, 2=In Progress, 6=Resolved, 7=Closed
    incident_category: "{{ category | default('Software') }}"
    incident_subcategory: "{{ subcategory | default('') }}"
    incident_caller_id: "{{ caller | default('') }}"
    incident_assignment_group: "{{ assignment_group | default('') }}"
    incident_assigned_to: "{{ assigned_to | default('') }}"

  tasks:
    - name: Validate required incident parameters
      ansible.builtin.assert:
        that:
          - incident_short_description is defined
          - incident_short_description | length > 0
        fail_msg: "incident_short_description is required and cannot be empty"
        success_msg: "Required parameters validated successfully"

    - name: Create ServiceNow incident
      servicenow.itsm.incident:
        state: new
        short_description: "{{ incident_short_description }}"
        description: "{{ incident_description }}"
        urgency: "{{ incident_urgency }}"
        impact: "{{ incident_impact }}"
        priority: "{{ incident_priority }}"
        category: "{{ incident_category }}"
        subcategory: "{{ incident_subcategory if incident_subcategory else omit }}"
        caller: "{{ incident_caller_id if incident_caller_id else omit }}"
        assignment_group: "{{ incident_assignment_group if incident_assignment_group else omit }}"
        assigned_to: "{{ incident_assigned_to if incident_assigned_to else omit }}"
        other:
          # Additional fields can be added here as needed
          opened_by: "{{ servicenow_username | default(ansible_servicenow_username) }}"
      register: incident_result

    - name: Display incident creation results
      ansible.builtin.debug:
        msg:
          - "Incident created successfully!"
          - "Incident Number: {{ incident_result.record.number }}"
          - "Incident Sys ID: {{ incident_result.record.sys_id }}"
          - "State: {{ incident_result.record.state }}"
          - "Priority: {{ incident_result.record.priority }}"
          - "Short Description: {{ incident_result.record.short_description }}"

    - name: Set incident facts for workflow use
      ansible.builtin.set_fact:
        created_incident_number: "{{ incident_result.record.number }}"
        created_incident_sys_id: "{{ incident_result.record.sys_id }}"
        created_incident_state: "{{ incident_result.record.state }}"
        created_incident_priority: "{{ incident_result.record.priority }}"

    - name: Save incident details to job artifacts
      ansible.builtin.set_stats:
        data:
          incident_number: "{{ incident_result.record.number }}"
          incident_sys_id: "{{ incident_result.record.sys_id }}"
          incident_state: "{{ incident_result.record.state }}"
          incident_priority: "{{ incident_result.record.priority }}"
          incident_url: "https://{{ servicenow_instance | default(ansible_servicenow_instance) }}/nav_to.do?uri=incident.do?sys_id={{ incident_result.record.sys_id }}"
        per_host: false
        aggregate: false

    - name: Log incident creation to file
      ansible.builtin.lineinfile:
        path: "/tmp/servicenow_incidents.log"
        line: "{{ ansible_date_time.iso8601 }} - CREATED - {{ incident_result.record.number }} - {{ incident_result.record.sys_id }} - {{ incident_short_description }}"
        create: true
        mode: '0644'
      delegate_to: localhost
      when: log_incidents | default(true) | bool

  handlers:
    - name: Send notification on incident creation
      ansible.builtin.debug:
        msg: "Incident {{ incident_result.record.number }} has been created and is ready for processing"
      listen: "incident_created"
