---
# Sub-playbook: Update ServiceNow Incident
# This file demonstrates how to update incidents using variables from parent workflow

- name: Update ServiceNow incident with provided configuration
  servicenow.itsm.incident:
    sys_id: "{{ target_incident.sys_id }}"
    assignment_group: "{{ update_config.assignment_group }}"
    work_notes: "{{ update_config.work_notes }}"
    other:
      state: "{{ update_config.state }}"
  register: updated_incident
  tags:
    - update_incident

- name: Load current shared variables
  ansible.builtin.include_vars:
    file: "{{ shared_vars_file_path }}"
    name: current_shared_data
  tags:
    - load_shared_vars

- name: Initialize processing results if not exists
  ansible.builtin.set_fact:
    processing_results: "{{ current_shared_data.processing_results | default({'updated': [], 'failed': []}) }}"
  tags:
    - init_results

- name: Add successful update to shared variables
  ansible.builtin.set_fact:
    updated_processing_results: >-
      {{
        processing_results | combine({
          'updated': processing_results.updated + [{
            'sys_id': target_incident.sys_id,
            'number': target_incident.number,
            'original_state': target_incident.state | default('unknown'),
            'new_state': updated_incident.record.state,
            'assignment_group': updated_incident.record.assignment_group,
            'updated_at': ansible_date_time.iso8601,
            'update_config': update_config
          }]
        })
      }}
  when: updated_incident is succeeded
  tags:
    - update_shared_vars

- name: Add failed update to shared variables
  ansible.builtin.set_fact:
    updated_processing_results: >-
      {{
        processing_results | combine({
          'failed': processing_results.failed + [{
            'sys_id': target_incident.sys_id,
            'number': target_incident.number,
            'error': updated_incident.msg | default('Unknown error'),
            'failed_at': ansible_date_time.iso8601,
            'attempted_config': update_config
          }]
        })
      }}
  when: updated_incident is failed
  tags:
    - update_shared_vars

- name: Update shared variables file with processing results
  ansible.builtin.copy:
    content: >-
      {{
        current_shared_data | combine({
          'processing_results': updated_processing_results
        }) | to_nice_yaml
      }}
    dest: "{{ shared_vars_file_path }}"
    mode: '0644'
  when: updated_processing_results is defined
  tags:
    - save_shared_vars

- name: Display update result
  ansible.builtin.debug:
    msg:
      - "{% if updated_incident is succeeded %}✅ Successfully Updated{% else %}❌ Failed to Update{% endif %}: {{ target_incident.number }}"
      - "Sys ID: {{ target_incident.sys_id }}"
      - "{% if updated_incident is succeeded %}New State: {{ updated_incident.record.state }}{% endif %}"
      - "{% if updated_incident is succeeded %}Assignment Group: {{ updated_incident.record.assignment_group }}{% endif %}"
      - "{% if updated_incident is failed %}Error: {{ updated_incident.msg | default('Unknown error') }}{% endif %}"
  tags:
    - display_result
